language: cpp
compiler:
  - clang
  - gcc

dist: trusty
sudo: false

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - g++-4.9
      - libc++1
      - libc++-dev

script:
  - make test CFLAGS="-O2 -coverage" CXX=${CXX}

after_success:
  - bash <(curl -s https://codecov.io/bash)
