language: cpp
compiler:
  - clang

dist: trusty
sudo: false

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - libc++1
      - libc++-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval "$(pyenv init -)"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install 2.7.6; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv global 2.7.6; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv rehash; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install cpp-coveralls; else pip install --user cpp-coveralls; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv rehash; fi

script:
  - make test CFLAGS="-O2 -coverage" CXX=${CXX}

after_success:
  - coveralls  -t DcluU4eNb0fYJrVslE8kUyEOnl9sMMrSE --exclude dependencies --exclude src/test-case --exclude include/asio --exclude include/ef.gy --gcov-options '\-lp'
