language: cpp
compiler:
  - clang
  - gcc

dist: bionic
sudo: false

os:
  - osx
  - linux

env:
  - CFLAGS="-O2 -coverage"
  - CFLAGS="-O0 -coverage"

addons:
  apt:
    packages:
      - libc++1
      - libc++-dev

script:
  - make test CFLAGS="${CFLAGS}" CXX=${CXX} DEBUG=true

after_success:
  - bash <(curl -s https://codecov.io/bash)
